config/routes.rb
SavelingWeb::Application.routes.draw do
  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users do
    resources :items
  end
  resources :items
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.has_role? :admin
      can :manage, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    can :manage, Item, owner_id: user.id
    can :read, Item
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_and_belongs_to_many :items
end

app/models/item.rb
class Item < ActiveRecord::Base
  has_and_belongs_to_many :categories
  has_many :images, class_name: 'ItemImage'

  monetize :price_cents

  accepts_nested_attributes_for :images
  belongs_to :owner, class_name: 'User'
  belongs_to :borrower, class_name: 'User'
end

app/models/item_image.rb
class ItemImage < ActiveRecord::Base
  belongs_to :item

  mount_uploader :image, ItemImageUploader

end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :avatar, AvatarUploader
  has_many :items, foreign_key: :owner_id
  geocoded_by :creation_ip
  after_validation :geocode
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, :alert => exception.message
  end

  def after_sign_in_path_for(resource)
    user_items_path(current_user)
  end


  before_filter do
    resource = controller_name.singularize.to_sym
    method = "#{resource}_params"
    params[resource] &&= send(method) if respond_to?(method, true)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @items = Item.joins(:images).all

  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  load_and_authorize_resource
  skip_authorize_resource :only => :new

  def index; end

  def new
    @item = Item.new
    @item.images.build
  end

  def show
    @item = Item.find(params[:id])
    render :show, layout: false
  end

  def create 
    @item = Item.create(item_params.merge(owner: current_user))
    redirect_to user_items_path(current_user)
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item.update_attributes(item_params)
    @item.save!
    redirect_to user_items_path(current_user)
  end

  def destroy
    @item.delete
    redirect_to user_items_path(current_user)
  end

  private

  def item_params
    params.require(:item).permit(:name, :description, :price, images_attributes: [ :image ])    
  end 
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_filter :update_sanitized_params, if: :devise_controller?

  def update_sanitized_params
    devise_parameter_sanitizer.for(:sign_up) {|u| u.permit(:name, :email, :password, :password_confirmation)}
    devise_parameter_sanitizer.for(:account_update) {|u| u.permit(:name, :email, :password, :password_confirmation, :current_password, :avatar, :avatar_cache)}
  end

  def create
    build_resource(sign_up_params.merge(creation_ip: request.ip))

    if resource.save
      if resource.active_for_authentication?
        set_flash_message :notice, :signed_up if is_navigational_format?
        sign_up(resource_name, resource)
        respond_with resource, :location => after_sign_up_path_for(resource)
      else
        set_flash_message :notice, :"signed_up_but_#{resource.inactive_message}" if is_navigational_format?
        expire_session_data_after_sign_in!
        respond_with resource, :location => after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      respond_with resource
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
  
  def update
    authorize! :update, @user, :message => 'Not authorized as an administrator.'
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user], :as => :admin)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end
    
  def destroy
    authorize! :destroy, @user, :message => 'Not authorized as an administrator.'
    user = User.find(params[:id])
    unless user == current_user
      user.destroy
      redirect_to users_path, :notice => "User deleted."
    else
      redirect_to users_path, :notice => "Can't delete yourself."
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def display_base_errors resource
    return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&#215;</button>
      #{messages}
    </div>
    HTML
    html.html_safe
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.slim
.row.collapse
  .large-1.columns#categories.grey-float.hide-for-touch data-0="top: 100px;" data-80="top: -17px;"
    ul
      - Category.all.each do |cat|
       li.category
          = link_to '&nbsp;'.html_safe, "##{cat.name.parameterize}", id: cat.name.parameterize
  .large-12.columns
    .row
      .large-6.columns.grey-float.large-centered#search-box
        = simple_form_for :search, :url => '/search' do |f|
          .row
            .large-6.columns
              = f.input :item, required: false, label: false, placeholder: 'riding lawn mower'
            .large-6.columns
              .row
                .small-8.columns
                  = f.input :city, input_html: { value: request.location.try(:city) }, required: false, label: false
                .small-4.columns
                  = f.submit 'Go!', class: 'button radius'
    .row
      .large-12.columns
        #masonry
          - @items.each do |item|
            = link_to item, class: 'box grey-float', data:{ reveal_id: "my-modal", reveal_ajax: "true"} do
              .row
                .small-12.columns= image_tag(item.images.first.try(:image_url, :medium238))
              .row
                .small-12.columns= item.name
              .row
                .small-12.columns= humanized_money_with_symbol(item.price) + "/week"
          / ul.large-block-grid-4
          /   - @items.each do |item|
          /     li.grey-float 
          /       span= item.name

app/views/items/edit.html.slim
.span8
  .row
    h3 Edit Item
  .row
    = simple_form_for @item, html: {multipart: true} do |f|
      = f.simple_fields_for :images do |i|
        = i.input :image_url
        = i.label 'Add Image'
        = i.file_field :image, label: 'Add Image'
        = i.hidden_field :image_cache
      = f.input :name
      = f.input :description
      = f.input :price
      = f.submit
  .row
    h3 Current Images
    - @item.images.each do |img|
      span= image_tag img.image_url(:thumb)

app/views/items/index.html.slim
h3 Items
.span8
  span= link_to("Add Item", { controller: "items", action: "new" })
  table.table.table-condensed
    thead
      tr
        th Name
        th Description
        th Thumbnail
        th Admin
    - current_user.items.each do |i|
      tr
        td= i.name
        td= i.description
        td= image_tag i.images.where('image is NOT NULL').first.try(:image_url, :thumb) if i.images.present?
        td
          = link_to 'Edit', edit_item_path(i)
          '|
          = link_to 'Delete', item_path(i), confirm: 'Are you sure?', method: :delete

app/views/items/new.html.slim
h3 Add Item
.span8
  = simple_form_for @item, html: {multipart: true} do |f|
    = f.simple_fields_for :images do |i|
      = i.file_field :image
      = i.hidden_field :image_cache
      = f.input :name
      = f.input :description
      = f.input :price
      = f.submit

app/views/items/show.html.slim
.row.item.show
  .large-3.columns
    = image_tag @item.images.first.image_url(:medium238)
  .large-9.columns
    .row
      .large-12.columns.text-right
        h2= @item.name
    .row
      .large-12.columns.end  
        p= @item.description
    .row
      .large-9.columns.large-centered
        .hd
    .row 
      .large-7.columns
        .price= humanized_money_with_symbol(@item.price) + "/week"
      .large-5.columns
        .row
          .large-8.columns.large-centered= image_tag @item.owner.try(:avatar_url, :small80)
        .row
          .large-12.columns.large-centered= @item.owner.name

app/views/layouts/_messages.html.slim
- flash.each do |name, msg|
  - if msg.is_a?(String)
    = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.slim
nav.top-bar  
  ul.title-area
    li.name= link_to image_tag('saveling.png'), root_path
  section.top-bar-section.left
    ul
      li.tagline Share Your Stuff. Borrow Theirs.
  section.top-bar-section.right
    ul
      - if user_signed_in?
        li
          = link_to 'My Stuff', user_items_path(current_user)
        li
          = link_to 'Logout', destroy_user_session_path, :method=>'delete'
      - else
        li
          = link_to 'Sign In', new_user_session_path
      - if user_signed_in?
        li
          = link_to 'Edit account', edit_user_registration_path
        - if current_user.has_role? :admin
          li
            = link_to 'Admin', users_path
      - else
        li |
        li
          = link_to 'Create Account', new_user_registration_path

app/views/layouts/application.html.slim
doctype html
html
  head
  meta content="width=device-width, initial-scale=1.0" name="viewport" 
    title= content_for?(:title) ? yield(:title) : "Saveling Web"
    meta content=(content_for?(:description) ? yield(:description) : "Saveling Web") name="description" 
    link href='http://fonts.googleapis.com/css?family=Allerta' rel='stylesheet' type='text/css'
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true 
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
    = yield(:head)
  body#skrollr-body class=("#{controller_name} #{action_name}") 
    #container.container data-0="background-position:0px 0px;" data-1000000="background-position:0px -50000px;"
      header
        = render 'layouts/navigation'
        = render 'layouts/messages'
      #main.row role="main"
        .large-12.columns 
          = yield
    / .row
    /   #background 
    footer#footer
      .row 
        .large-6.columns.large-centered
    /! ! end of #container
    #my-modal.reveal-modal.medium.grey-float
  javascript:
    rumbleBannerPlacement = "bottom";
  = javascript_include_tag "http://s0.railsrumble.com/banner.js"

app/views/users/_user.html.slim
.modal id="role-options-#{user.id}" style=("display: none;") 
  = simple_form_for user, :url => user_path(user), :html => {:method => :put, :class => 'form-horizontal' } do |f|
    .modal-header
      a.close data-dismiss="modal"  ×
      h3 Change Role
    .modal-body
      = f.input :role_ids, :collection => Role.all, :as => :radio_buttons, :label_method => lambda {|t| t.name.titleize}, :label => false, :item_wrapper_class => 'inline', checked: user.role_ids.first
    .modal-footer
      = f.submit "Change Role", :class => "btn"
      a.btn data-dismiss="modal" href="#"  Close

app/views/users/index.html.slim
h3 Users
.span8
  table.table.table-condensed
    thead
      tr
        th Username
        th Email
        th Registered
        th Role
        th
        th
    tbody
      - @users.each do |user|
        tr
          td= link_to user.name, user
          td= user.email
          td= user.created_at.to_date
          td= user.roles.first.name.titleize unless user.roles.first.nil?
          td
            a.btn.btn-mini data-toggle="modal" href="#role-options-#{user.id}" type="button"  Change role
            = render user
          td= link_to("Delete user", user_path(user), :data =>   confirm=("Are you sure?" ) , :method => :delete, :class => 'btn btn-mini') unless user == current_user

app/views/users/show.html.slim
h3 User
p
  | User: #{@user.name}
p
  | Email: #{@user.email if @user.email}